# borrowed and very lightly modified from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
#       and https://docs.cypress.io/guides/continuous-integration/github-actions
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress Tests
        uses: cypress-io/github-action@v5.3.1 # https://github.com/marketplace/actions/cypress-io
        with:
          build: npm run build
          start: npm start
